name: napari-big-data-training
channels:
  - conda-forge
dependencies:
  - scikit-image
  - jupyterlab
  - tifffile
  - imagecodecs
  - napari
  - zarr
  - dask
  - dask-labextension
  - dask-image=0.5.0
  - python-graphviz
  - matplotlib
